### ISSUE TITLE
UAT | The View Document button needs to look like a link

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1506]
Nyay Mitra screen -> Open View Registrations -> View Requests -> CLick on any application number-> Scroll down below the uploaded document pic

![Image](https://github.com/user-attachments/assets/58fb2146-02d0-48b3-b05b-3d1bffee2860)

**Comment by rsi-MaheshVishwanath** [comment]
Hi @shambhavigoel1002, one more issue related to this ticket is about the advocate registrations: https://github.com/pucardotorg/dristi/issues/1541 Can you please check it out? thanks!

**Comment by rsi-MaheshVishwanath** [comment]
Retested in "Solution QA," now this document button is looking like a link. Thanks!
https://jam.dev/c/967a6e0d-75df-4b13-b84b-db94fd977511

**Comment by rsi-MaheshVishwanath** [comment]
Hi @devarajd94 @Taherabharmal, 

Descriptions: When nyay mitra gave to approval for the new registration's users like advocate, what are the document user upload his registration time like any jpg or pdf file it has been showing nyay mitra side so that document he should view this button should show as link.

Test Cases:
1) Verify that Nyay Mitra can view documents as a link for newly registered users at the time of approving their registration
2)  Verify that Nyay Mitra can view documents as a link for old users at the time of approving their registration

Reference Link: https://jam.dev/c/967a6e0d-75df-4b13-b84b-db94fd977511
Advocate url: https://dristi-kerala-qa.pucar.org/digit-ui/citizen/select-language
Nyay Mitra url :https://dristi-kerala-qa.pucar.org/digit-ui/employee/user/login
nyay mitra users:https://docs.google.com/spreadsheets/d/16X9l89-YwhojBw6bkiqj3mZhf_loQ7P5BPHsCYCVZbg/edit?gid=574770155#gid=574770155

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla ,kindly verify this:
  - Regarding_"View Document" link
  - Env.UAT
  - url: https://dristi-kerala-uat.pucar.org/digit-ui/employee/dristi/registration-requests/details?applicationNo=ADV-APP-2024-09-10-000156&individualId=IND-2024-09-10-000067&type=advocate
  - reference link: https://jam.dev/c/fd91c9f4-8b3f-4c86-a6c6-69685c5da82f

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  this issue is fixed and please verify and confirm
