### ISSUE TITLE
Bug | Document Submission screen pops up everytime a pending task is closed

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1640]
https://github.com/user-attachments/assets/b75819a9-20ca-4e99-9c10-ff55c953e6cc

**Comment by Ramu-kandimalla** [comment]
Hi @shambhavigoel1002  Please add the development tasks and estimated effort details to resolve this ticket

**Comment by shambhavigoel1002** [comment]
HI@Ramu-kandimalla 
Seems like this issue is resolved below is reference video

https://beehyv0-my.sharepoint.com/personal/bhuvanyu_guru_beehyv_com/_layouts/15/stream.aspx?id=%2Fpersonal%2Fbhuvanyu%5Fguru%5Fbeehyv%5Fcom%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files%2Fpending%20%5Ftask%2Dsummons%5F9%5Fsept%2Ewebm&referrer=Teams%2ETEAMS%2DWEB&referrerScenario=p2p%5Fns%2Dbim&ga=1

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  please check and confirm in UAT environment

**Comment by rajeshcherukumalli** [comment]
Hi @devarajd94 , issue is fixed in UAT environement , please find the reference
https://jam.dev/c/52f5d44e-940b-4496-bdd6-56b47c262377
