### ISSUE TITLE
SDC Monitoring Tools

### ISSUE THREAD

**Issue by Ramu-kandimalla** [pucardotorg/dristi#1652]
- [ ] Understand the Monitoring Tools in SDC and Check whether these tools serve our requirement

**Comment by Pasam6** [comment]
Asked for Walk-Through on the existing SDC Monitoring Tools:
Focused Requirements:
1. How to view memory/cpu consumption against the requested memory/cpu . (Able to view only the consumption)
2. Need more info how we can configure Alerts (if 80% of requested limit is exceeded)
3. Regarding the kibana , from which elastic search we are getting data?
4. For debugging we need message, service (Not there), timestamp, log and logtype(not able to specify warn, fatal etc) indexes.

**Comment by Pasam6** [comment]
This ticket will be closed based on the availability of SDC team.

**Comment by Pasam6** [comment]
SDC raised a ticket with Redhat regarding monitoring tools.
Redhat Response:
https://access.redhat.com/solutions/6615991
""From the case I am able to understand that you are using inbuilt grafana and the user data is not available.

Unfortunately, the grafana has been depricated and has been removed since 4.11.  
- https://access.redhat.com/solutions/6615991

And as per your requirement you want to enable monitoring for specific namespaces, so you could check the user-workload-monitoring which does the similar job as per your requirement:
- https://docs.openshift.com/container-platform/4.14/observability/monitoring/enabling-monitoring-for-user-defined-projects.html""


So we are going to deploy DIGIT monitoring tools in SDC for production.
