### ISSUE TITLE
Localisation: Id-Verification string is grammatically wrong

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#167]
Env: UAT
In the user registration screen, "Id-verification" is grammatically wrong. Should be "ID Verification". Also "ADHAR" should be rewritten as "AADHAR". Let's use correct grammar and language.
<img width="947" alt="Screenshot 2024-05-02 at 6 47 38 PM" src="https://github.com/pucardotorg/dristi/assets/107110442/78d94ea2-d5a5-4618-8917-64d0700859e9">

**Comment by SureshSoren** [comment]
Fixed and pushed to UAT

**Comment by Vanshikajain02** [comment]
Steps to Reproduce

1. Enter the Mobile Number
2. Enter the username
3. Enter the OTP sent on mobile number
4. Click on the drop down arrow for Id proof
5. Check the spelling of Adhar

Expected Behaviour
It should be "AADHAR" instead of "ADHAAR"

Actual Result
Working fine as expected (In dev environment)
