### ISSUE TITLE
Sept Demo | Case Numbering

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1684]
Refer Ticket[ Link](https://github.com/orgs/pucardotorg/projects/1/views/2?filterQuery=1535&pane=issue&itemId=78247557)

**Comment by Mahesh-Vishwanath1** [comment]
Hi @devarajd94,
For this ticket, test cases related to the UI side should focus on verifying the case numbering update (Solution UAT).

Test Cases:
1.Verify Filing Number used for Case (The filing number should be generated in the format [STATE]-[XXXXXX]-[cy
], e.g., **KL-000001-2024**. The sequence number should be 6-digit padded and should reset to "000001" on January 1 of each year.)
2.Verify that a unique CNR Number is generated for each case registered (A unique CNR Number should be generated in the format **[STATE][DISTRICT][ESTABLISHMENT][XXXXXX][cy]**, where XXXXXX is a 6-digit sequence that resets every Jan 1)
3.Verify the generation of cmpNumber with unique sequence and no padding (The cmpNumber should be generated as **CMP/1/2024**, where 1 is the sequence number starting from 1, specific to the State-District-Establishment combination.)
4.Verify court case number generation for Summary Trial (ST) and Calendar Case (CC) :( The system should generate the case number in the format:
- **ST/1/2024** for Summary Trials
- **CC/1/2024** for Calendar Cases without padding)
5.Verify advocate registration ID sequence format and remain unique across the state (The advocate ID generated should follow the format **KL-ADV-[Sequence]-[Year], e.g., KL-ADV-000001-2024**. The sequence number should reset every January 1st and remain unique across the state. The sequence should not reset daily and should have no padding for the sequence number.)
6.Verify unique Clerk Registration ID generation with correct format (The system should generate a registration ID in the format **KL-CLERK-000001-2024** where: **KL-CLERK** is static, the sequence resets every Jan 1, but no daily reset or padding applied)
7.Verify that the ApplicationNumber is generated in the correct format: **CNR-AP[X]** and resets every 1st Jan (1. Application number should follow the format: **CNR-AP[X]**. 2. Sequence should be unique across country, reset every 1st Jan, and be the same for establishment.)
8.Verify Hearing Number format and uniqueness (**Format: CNR-HR[X] Ex. KLKM520000012024-HR12, SEQ_HEARING: 1**)
9.Verify Order Number format. (Unique SEQ_ORDER should be generated based on CNR and specific sequence logic ex. Order Number: **CNR-OR5, Unique Seq: KLKM520000012024-OR5**)
10. Verify task creation with unique CNR-TK and sequence number. (Task is created successfully with a unique TaskNumber specific to the state, district, and establishment. **Format: CNR-TK1 Ex. KLKM520000012024-TK1** SEQ_TASK: 1)
11. Verify the generation of a unique SummonsID.(Summons ID should be generated in the format: **CNRSM[X]**KLKM520000012024-SM4 SEQ_SUMMONS with unique sequence number) (Not implemented)
12. Verify unique WarrantID generation. (WarrantID should be unique across the specified state, district, and establishment **ex. WarrantID: CNR-WR5, SEQ_WARRANT: 001**) (Not implemented)
13. Verify unique BailID generation for a new case. (Generated BailID should be unique and formatted correctly based on input **format: CNR-BL[X] Ex. KLKM520000012024-BL1**) (Not implemented)
14.Verify that the prosecution artifact/evidence sequence number is unique per case and displayed correctly **(Format: CNR-P[X]
KLKM520000012024-P1,
KLKM520000012024-P2)**
15.Verify that the Defence (Respondent) Artifact/Evidence sequence number is correctly generated and displayed for a case. (**Format: CNR-D[X]
ex. KLKM520000012024-D1,
KLKM520000012024-D2**)
16.Verify court submitted artifact/evidence number for a case is displayed correctly based on the sequence. (**Ex. CNR-C[X]
KLKM520000012024-C1,
KLKM520000012024-C2**) (Not implemented)
17.Verify that the Prosecution Witness sequence number is correctly displayed for a case. (**Format CNR-PW[X]
ex. KLKM520000012024-PW1**)(Not implemented)
18.Verify Défense Witness sequence number for a case. (**Format CNR-DW[X] ex. KLKM520000012024-DW1**)(Not implemented)
19.Verify that the Court Witness sequence number resets per case and is displayed without the CNR prefix in the final judgement (**format CNR-CW[X] ex. KLKM520000012024-CW1**)(Not implemented)
20.Verify that the sequence number for prosecution artifact and evidence is correctly displayed (**Format: CNR-P[X]
ex. KLKM520000012024-P3**) (Not implemented)
21.Verify formatting and visibility of Defence Witness Deposition number in Judgement (**Format: CNR-D[X]
ex. KLKM520000012024-D3**) (Not implemented)
22.Verify visibility and format of Court Witness deposition evidence number (**Format: CNR-C[X]
ex.KLKM520000012024-C3** )(Not implemented)

open issues:
1.https://github.com/pucardotorg/Dristi_kerala/issues/1100
2.https://github.com/pucardotorg/Dristi_kerala/issues/1116
3.https://github.com/pucardotorg/Dristi_kerala/issues/1111 (This issue was raised before the change in application IDs.)

Reference link: https://jam.dev/c/c3b1060b-9980-472d-aa85-059007b4d00c

User Ids link: https://docs.google.com/spreadsheets/d/1w0RT8lHfx7T2-WaTW2DS-66THYjtyNYTw-FDoqJp5-o/edit?gid=0#gid=0

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and Confirm

**Comment by devarajd94** [comment]
Verified
