### ISSUE TITLE
UAT Feedback | RPAD Payment | Amount to be mentioned as '-' as it is stamp payment basis

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1724]
The Delivery Partner Fee to be updated as a '-' as opposed to Rs 100. Court fee should be shown 

(The calculated channel fee is applicable only to EPOST and not Registered Post)

![Image](https://github.com/user-attachments/assets/9060df12-9e17-42f2-ae21-f5ce0a88ffec)

**Comment by shambhavigoel1002** [comment]
HI @devarajd94  can you please elaborate with an example. Still not clear with requirement 
cc :- @Ramu-kandimalla

**Comment by shambhavigoel1002** [comment]
Changes done Please check @rajeshcherukumalli 
cc:- @Ramu-kandimalla

**Comment by Mahesh-Vishwanath1** [comment]
Hi @devarajd94,
I have verified this ticket in the UAT solution, confirming that the Delivery Partner Fee is now correctly displayed as '-' instead of Rs 100, and the Court fee is shown as expected.
(Important note: The Court fee is currently displayed as Rs 5. The development team is working on updating it to reflect the correct fee.)

Refrence link: https://jam.dev/c/11f35799-096c-4971-93fe-bb0b8d4e2ca7
<img width="960" alt="payment" src="https://github.com/user-attachments/assets/647d49c6-6a42-4fda-abb6-b2765fbbfc2a">

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  this issue is fixed
