### ISSUE TITLE
[BUG]: Order Issuance button not working

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1800]
**Describe the bug**

- [ ] After ending admission hearing, the Admit case button was still active. 
- [ ] I went to home screen and clicked on the pending task to admit case. It showed Issue Order. But the button is not working

**To Reproduce**

https://github.com/user-attachments/assets/3e8868cd-afde-43e2-8f72-2d390aa0fd83

**Comment by anirudh-0** [comment]
@devarajd94 
1. Ending admission hearing will not admit the case automatically so admit case will be active.
2. for this, judge has to create an admission hearing again before issuing a notice. This happened because admission hearing was started and ended before notice was issued. How do you want us to handle this scenario ? The option we're thinking of is we don't allow start of admission hearing until notice is issued.

**Comment by devarajd94** [comment]
@anirudh-0 that is understood. But at the end of the previous admission hearing I schedule the next hearing. Then again I click on Admit Case, then it schedules hearing - I try to schedule hearing it shows hearing already scheduled. Then I come to home screen, see the button as Issue Order.

**Comment by vaibhavct** [comment]
@devarajd94 
I've checked the filingNumber which you've used in the video, There is not order published for schedule next hearing, hence no hearing is scheduled.

> I try to schedule hearing it shows hearing already scheduled.

I'm not able to reproduce this message, can you please provide some details.
c.c. @anirudh-0

**Comment by vaibhavct** [comment]
How shall we proceed @devarajd94 ?
c.c. @Ramu-kandimalla
