### ISSUE TITLE
UAT Bug | Reselecting Document

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#195]
Module: User Registration
User: Litigant, Advocate
Screen: ID Verification

Issue: Once a document is selected, it cannot be deselected. On clicking the cross beside the file name - an option to reselect a doc is shown. On selection of any other docs, an error is shown

Recording: 

Expected behaviour: 
1) Document should be removed on clicking the cross beside the file
2) Selection of other files should be possible

**Comment by SureshSoren** [comment]
@Taherabharmal  The current upload document digit component that we are using has limiter in which we restrict the no. of document we want to upload and since we have to send only one document we have set a limit to 1 so when we are upload another document on top of it it's showing an error. 

cc: @manimaarans  @krishnaprasadsannidhi

**Comment by Vanshikajain02** [comment]
Working fine in dev environment now
