### ISSUE TITLE
UAT Bug | Take Action Button

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#201]
Module: User Registration
User: Nyay Mitra

Issue:
On entering a registration request by clicking on the ID in the List of Registration requests, the user is redirected to details of registration. However the Take Action Button is missing and the user is only displayed Go to Home as a button

Expected behaviour:
Take action button is displayed for user to approve or reject requests

**Comment by Beehyv-Vinod** [comment]
Steps for the issue

1. Login as Nyayamitra
2. Click on the Application number
3. Check that the "Take action" button is displayed in the bottom right corner..

Expected: "Take action" button should display instead of the "Go to Home".

Status: Working as Expected in dev environment, "Take action" button is displaying first time, Once the action is taken, the 'Go to Home' button appears.

**Comment by Taherabharmal** [comment]
resolved
