### ISSUE TITLE
[UAT]: Replace the Join Conference Link

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#2033]
**Describe the bug**
Replace the video conferencing link with the following link:
https://business.vconsol.com/join/9372021453?be_auth=NjQxMjU3 

To be done for litigants, advocates, judge

https://github.com/user-attachments/assets/9ab8c6f1-ff81-4bc5-8e0b-f0db2aac3a36

**Comment by bhuvanyuguru** [comment]
Hi @devarajd94, @Ramu-kandimalla, 

This bug is resolved in **QA**. 

- Verified and Tested for Judge,Advocate and Litigant.

Attaching Screenshots for reference. 

![image](https://github.com/user-attachments/assets/47dd37a1-b7d1-4fb0-b6ee-e5e5866ed4ae)

[UI redirect in hearing.webm](https://github.com/user-attachments/assets/1e49bf95-c3be-4c23-8dfa-c6e43cc4a46c)


CC: @rajeshcherukumalli

**Comment by devarajd94** [comment]
Verified
