### ISSUE TITLE
[BUG]: [QA] When FSO Sent the case back for correction Case Stage showing as Filing

### ISSUE THREAD

**Issue by Beehyv-Vinod** [pucardotorg/dristi#2070]
**Describe the bug**
When FSO Sent the case back for correction Case stage showing as Filing, Even if Complainant edit's the details & if submit's the case, Stage showing as Filing Only

**To Reproduce**
1. File a case
2. Move the case to FSO
3. From FSO Send the case back for the Correction
4. Now we can see case stage showing as Filing
5. Resubmit the case by complainant
6. Now we can see case stage still showing as Filing only for both FSO & Complainant  

**Expected behavior**
Case stage should be Scrutiny

Ref,
https://jam.dev/c/83b6d45e-cfbb-42f2-bd00-92da975fd833

**Comment by Beehyv-Vinod** [comment]
Same issue when Judge Sent case back for the correction.

**Comment by nileshgupta111** [comment]
1. Due to two actions with same name case stage is not updating correctly. So added check for status along with actions
2. Currently only implemented this logic for case, might have to for other modules in case of similar issue

PR for the changes - https://github.com/pucardotorg/dristi-solutions/pull/672

**Comment by bhuvanyuguru** [comment]
Hi @nileshgupta111 This bug is not fixed in QA 

Advocate , litigant and FSO are getting stage as Filing. 

Attaching reference screenshots. 

![image](https://github.com/user-attachments/assets/2cba9232-5fa1-4d79-a257-35fcb1a0f742)


![image](https://github.com/user-attachments/assets/6a6131f4-e35f-480b-839a-83edd16f391f)


CC: @Ramu-kandimalla, @manimaarans

**Comment by Beehyv-Vinod** [comment]
Hi @nileshgupta111  Tested in Kerala-qa, It is not working as expected.

**Comment by nileshgupta111** [comment]
@Beehyv-Vinod  fixed it, check again

**Comment by rajeshcherukumalli** [comment]
Hi @nileshgupta111 , same issue is still exists.

**Comment by Beehyv-Vinod** [comment]
Tested in kerala-QA working fine except the Refresh issue.
Issue- https://github.com/pucardotorg/dristi/issues/1969

**Comment by Beehyv-Vinod** [comment]
Tested in UAT environment, Working as expected
