### ISSUE TITLE
[BUG]: Invalid Address, requires atleast 2 characters error message is displayed if we didn't enter any address in the field 

### ISSUE THREAD

**Issue by rajeshcherukumalli** [pucardotorg/dristi#2463]
At User registration, user didn't provide any address and try to register system accepting.

Login with the same user , and try to file a case system not allowed user to file a case.

![Screenshot from 2024-11-18 14-52-03](https://github.com/user-attachments/assets/f8b0f7a3-7764-4840-ae03-d8c4c725ce5f)

**Comment by ashishbeehyv** [comment]
Issue: at the time of registration, there is locality/street name field which didn't have any validation for min characters, but if we enter 1 or no character here, it will give validation error in efiling "ADDRESS" field because that is having mandatory filed with min 2 characters validation and it is obtained by combining the locality, building Name and door number field values from registration form(this is how the logic is present).

Changes Made: made address field "optional" in efiling also added min 2 characters validation for locality/street name field during registration.

cc: @rajeshcherukumalli  @Ramu-kandimalla

**Comment by rajeshcherukumalli** [comment]
Hi @Ramu-kandimalla , issue is resolved in DPG-DEV
![Screenshot from 2024-11-18 19-14-07](https://github.com/user-attachments/assets/7a89072c-f1a9-4792-8fd4-113c72eb59d3)
