### ISSUE TITLE
PROD SUPPORT : Rejected an advocate registration request but still appearing 

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2595]
**Describe the bug**
Rejected an advocate registration request but still appearing

**Comment by Susmitabe** [comment]
@rajeshcherukumalli  can we try to reproduce  this in UAT?

**Comment by bhuvanyuguru** [comment]
Hi @anirudh-0, @rajeshcherukumalli 

This Bug is reproduced in UAT, 

After rejection for an Advocate, The Record is still being shown in the table. 

If we refresh the window, record is gone. 

Refer Screenshot

![image](https://github.com/user-attachments/assets/22721690-290a-448c-bc85-4d83bec78b4c)

**Comment by shambhavigoel1002** [comment]
Hi @manimaarans 
After an adovcate application is rejected proper update call is happening with proper workflow actions. And after that when it goes to home screen /inbox/v2/_search is called and Is still giving response with previous application . To me it seems there's lag in update of the response. Because after refresh response is correct. 
cc @Ramu-kandimalla  , @Susmitabe

**Comment by subhashini-egov** [comment]
@manimaarans is this always reproducible? Have we increased memory allocation for indexer and ES and tried this? can we introduce a pop up that says "application has been rejected" and let the user click on "OK" before redirecting them to the home screen.

**Comment by atulgupta2024** [comment]
@manimaarans @shambhavigoel1002 can you help trace the calls, events that happen in this path, or point me to which method should I look in the code  - advocate/update or something else?

**Comment by atulgupta2024** [comment]
@manimaarans are we still using inbox V2 for NM registration list screen? 

also i was looking at the 'advocate-index-test' index in Elastic. It has the same fields as that of Advocate entity (except workflow and documents). Did we create the index because inbox v2 required it or for some other reason?

**Comment by atulgupta2024** [comment]
@manimaarans @shambhavigoel1002 what if we totally move away from Indexer in advocate (clerk) approvals? 
The NM screen for pending registrations can be loaded using the following API 

`  /advocate/v1/status/_search:`

The click on verify and getting details of a specific application can happen via the following API 

`  /advocate/v1/applicationnumber/_search:`

After verification, we can call the   /advocate/v1/_update to update the approval/rejection status 

Will this work?

**Comment by subhashini-egov** [comment]
@manimaarans @atulgupta2024 We can use the search APi to populate the NM's inbox instead of Inbox v2. Just think through the whole flow once. WE might run into performance problems when there's a lot of entries in the DB. So indexing should be proper in DB.

**Comment by atulgupta2024** [comment]
The search is mostly based on status. @manimaarans do we have index on status column in advocate table? Can you share what indexes are set?

**Comment by Ramu-kandimalla** [comment]
Hi @Susmitabe  This will be product enhancement please get this reviewed by @atulgupta2024  @ansh-egov  @Taherabharmal  @suresh12

**Comment by atulgupta2024** [comment]
@manimaarans do note that I am referring DB index and not ES index. We need to ensure our DB tables have relevant indices enabled.

**Comment by Ramu-kandimalla** [comment]
Hi @Susmitabe @devarajd94 @ansh-egov @mehulseg24  Please take this as a new feature in upcoming sprints

**Comment by Susmitabe** [comment]
This issue is not happening now
