### ISSUE TITLE
UAT | Security Bug | Join a case code visible

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#916]
Code to join a case along with additional case details available in network tab when searching for a case during the join a case process flow.

cc: @subhashini-egov @atul

**Comment by atulgupta2024** [comment]
@manimaarans please add @Exclude annotation for the accesscode field so that is not sent as part of response. 

@Ramu-kandimalla @suresh12 this is a 1 line change. should be taken up ASAP

**Comment by anirudh-0** [comment]
@atulgupta2024 if we exclude in code, then it would not be possible to test this flow in UAT unless the summons deliveries are implemented, i.e. some sms at least

**Comment by atulgupta2024** [comment]
let's ignore the issue since the access code is publicly visible on notice/summons anyway. and no one can sniff it over the wire. once the summary API is in place, the access code will not be visible at the time of join a case as well for anyone to find that out from the response info. 

@Ramu-kandimalla @anirudh-0 @suresh12 @subhashini-egov - my vote is to close this ticket.

**Comment by suresh12** [comment]
Concur with Atul on the decision to close this ticket.

**Comment by atulgupta2024** [comment]
closing
